'use client'
import { fonts } from "@/components/fonts";
import "@/styles/globals.css";
import { CacheProvider } from '@chakra-ui/next-js';
import { ChakraProvider } from "@chakra-ui/react";
import type { AppProps } from "next/app";
import Head from "next/head";
import { useEffect } from "react";

export default function App({ Component, pageProps }: AppProps) {
  useEffect(() => {
    const apiKey = 'NqBVVemHeec5UEpwXwlPZuNXownfCEPw';
    const endpoint = 'http://localhost:8000/api/monitor/activity';

    fetch(endpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-API-Key': apiKey,
      },
      body: JSON.stringify({
        ip_address: '10.25.87.15', // ideally resolved server-side
        method: 'GET',
        endpoint: window.location.pathname,
        response_code: 200,
        user_agent: navigator.userAgent,
        response_time: performance.now(),
      }),
    }).catch((err) => console.error('ThreatGuard:', err));
  }, []);

  return(
    <CacheProvider>
      <ChakraProvider>
        <main className={fonts.arvo.className}>
          <Head>
            <title>Delight Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Component {...pageProps} />
        </main>
      </ChakraProvider>
    </CacheProvider>
  );
}
