'use client'
import { fonts } from "@/components/fonts";
import "@/styles/globals.css";
import { CacheProvider } from '@chakra-ui/next-js';
import { ChakraProvider } from "@chakra-ui/react";
import type { AppProps } from "next/app";
import Head from "next/head";

export default function App({ Component, pageProps }: AppProps) {
  return(
    <CacheProvider>
      <ChakraProvider>
        <main className={fonts.arvo.className}>
          <Head>
            <title>Delight Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Component {...pageProps} />
        </main>
      </ChakraProvider>
    </CacheProvider>
  );
}
